name: GEOMETOR
motto: exploring<br>the foundation of<br>logical relationships
facebook: phi.architect
twitter: phi_architect
linkedin: phi-architect
youtube: UCYzRQS16EBmsbKuyKMFHSFQ
github: geometor
owa_siteid: d1039be9b72f9820624ec26ad1c2722a
google_search: bYQ6W9XS6CPkwqqn-S3jJUoVhwgwF7U6YHQrWQlkwgE
