name: GEOMETOR Euclid
motto: exploring<br>the foundation of<br>logical relationships
logo: elem.1.prop.1.png
email: info@geometor.com
social:
  facebook: phiarchitect
  twitter: phi_architect
  linkedin: phiarchitect
  youtube: UCYzRQS16EBmsbKuyKMFHSFQ
  github: geometor
owa:
  siteId: d5c4021db353705e494d8f0bb5c6fa9d
  trackPageView: true
  trackCLicks: false
  trackDomStream: false
google_search: rx3g9yar1U6omp_jO04YkOVZuZyNJO07d00DIHglZ1Q
